[workspace]
resolver = "2"
members = ["fcnet-types", "fcnet", "fcnet-cli", "fcnetd", "fcnetd-client"]

[profile.dev]
debug = false
strip = "symbols"

[profile.release]
lto = "fat"
strip = "symbols"
codegen-units = 1
