[workspace]
resolver = "2"
members = ["fcnet", "fcnet-use-integrated", "fcnet-serve-cli"]

[profile.dev]
debug = false
strip = "symbols"

[profile.release]
lto = "fat"
strip = "symbols"
codegen-units = 1
