[package]
name = "fcnet-core"
version = "0.1.0"
edition = "2021"

[dependencies]
cidr = "0.3.0"

[dev-dependencies]
fcnet-core = { path = ".", features = ["full"] }

[features]
simple = []
namespaced = []
full = ["simple", "namespaced"]
