[package]
name = "fcnet"
version = "0.6.0"
edition = "2021"

[dependencies]
cidr = "0.3.0"

[dev-dependencies]
fcnet = { path = ".", features = ["full"] }

[features]
simple = []
namespaced = []
full = ["simple", "namespaced"]
