[package]
name = "fcnet"
version = "0.5.1"
edition = "2021"
description = "A library for Firecracker microVM networking"
license = "MIT"
keywords = ["firecracker", "microvm", "networking"]
categories = ["network-programming"]
repository = "https://github.com/kanpov/fcnet"
readme = "README.md"

[package.metadata.docs.rs]
all-features = true

[dependencies]
tokio = { version = "1.40.0", features = ["process"] }
futures-util = { version = "0.3.31", default-features = false }
rtnetlink = "0.14.1"
netlink-packet-route = "0.19"
tokio-tun = "0.12.0"
cidr = "0.3.0"
thiserror = "1.0.64"

nix = { version = "0.29.0", optional = true, features = [
    "mount",
    "sched",
    "process",
] }

[dev-dependencies]
fcnet = { path = ".", features = ["namespaced"] }

[features]
default = ["simple"]
full = ["simple", "namespaced"]
simple = []
namespaced = ["dep:nix", "tokio/sync", "tokio/rt"]
