[package]
name = "fcnet"
version = "0.4.0"
edition = "2021"
description = "A library for Firecracker microVM networking"
license = "MIT"
keywords = ["firecracker", "microvm", "networking"]
categories = ["network-programming"]
repository = "https://github.com/kanpov/fcnet"
readme = "README.md"

[package.metadata.docs.rs]
all-features = true

[dependencies]
tokio = { version = "1.40.0", features = ["process"] }
futures-util = { version = "0.3.31", default-features = false }
rtnetlink = "0.14.1"
netlink-packet-route = "0.19"
tokio-tun = "0.12.0"
cidr = "0.3.0"

netns-rs = { version = "0.1.0", optional = true }
thiserror = "1.0.64"

[dev-dependencies]
fcnet = { path = ".", features = ["namespaced"] }

[features]
default = ["simple"]
full = ["simple", "namespaced"]
simple = []
namespaced = ["dep:netns-rs", "tokio/sync", "tokio/rt"]
